trigger:
- master

pool:
  name: 'batch11'   # your self-hosted Windows agent pool

stages:
# Stage 1: Build and Publish Artifacts
- stage: Build
  displayName: 'Build Project'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Package'
    steps:
    # Ensure Java is available (if needed on agent)
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # Run Maven build
    - task: Maven@4
      inputs:
        mavenPomFile: 'Amazon/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Debug - list files to confirm target directory
    - powershell: |
        Write-Host "Listing contents after Maven build..."
        Get-ChildItem -Path "$(Build.SourcesDirectory)\Amazon" -Recurse
      displayName: 'Verify Maven build output'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)\Amazon\target'
        artifactName: 'drop'
        publishLocation: 'Container'

# Stage 2: Deploy
- stage: Deploy
  displayName: 'Deploy Artifact'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Artifact Job'
    steps:
    # Download artifact from Build stage
    - download: current
      artifact: drop

    # Deploy to C:\deploy\Amazon
    - powershell: |
        Write-Host "Deploying artifact..."
        New-Item -Path "C:\deploy\Amazon" -ItemType Directory -Force
        Copy-Item "$(Pipeline.Workspace)\drop\*.jar" "C:\deploy\Amazon" -Force
        Write-Host "Deployment complete. Files in C:\deploy\Amazon:"
        Get-ChildItem "C:\deploy\Amazon"
      displayName: 'Copy artifact to deploy folder'
