trigger:
- master   # Trigger pipeline on commits to master

pool:
  name: batch11    # Your self-hosted Windows agent pool

stages:
# ------------------ Build Stage ------------------
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - checkout: self   # Pulls your GitHub repo

    # Create artifact folder and copy repo files
    - powershell: |
        Write-Host "Preparing build artifact..."
        New-Item -ItemType Directory -Path "$(Build.ArtifactStagingDirectory)" -Force
        Copy-Item -Path * -Destination "$(Build.ArtifactStagingDirectory)" -Recurse -Force
      displayName: "Copy repo files to staging directory"

    # Publish all repo files as an artifact
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: AmazonTestRepo
      displayName: "Publish Repo as Artifact"

# ------------------ Test Stage ------------------
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Run Tests"
    steps:
    - download: current
      artifact: AmazonTestRepo
    - powershell: |
        Write-Host "Running tests on downloaded artifact..."
        Get-ChildItem
      displayName: "Inspect Artifact"
