trigger:
- master

pool:
  name: 'batch11'   # your self-hosted Windows agent pool

stages:
# Stage 1: Build and Publish Artifacts
- stage: Build
  displayName: 'Build Project'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Package'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'Amazon/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
    - powershell: |
        Write-Host "Listing contents of Maven build output directory..."
        Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\Amazon\target" -Recurse
      displayName: 'List contents of build output'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Amazon/target'   # Must match Maven output directory
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Stage 2: Deploy
- stage: Deploy
  displayName: 'Deploy Artifact'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Artifact Job'
    steps:
    - download: current
      artifact: drop
    - powershell: |
        Write-Host "Deploying artifact..."
        Copy-Item "$(Pipeline.Workspace)/drop/*.jar" "C:\deploy\Amazon" -Force
      displayName: 'Copy artifact to deploy folder'
