trigger:
- master

pool:
  name: 'batch11'   # your self-hosted Windows agent pool

stages:
# Stage 1: Build and Publish Artifacts
- stage: Build
  displayName: 'Build Project'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Package'
    steps:
    # Run Maven build
    - task: Maven@4
      inputs:
        mavenPomFile: 'Amazon/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Verify target folder contents
    - powershell: |
        Write-Host "Listing contents of Maven build output directory..."
        Get-ChildItem -Path "$(Build.SourcesDirectory)\Amazon\target" -Recurse
      displayName: 'List contents of build output'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoP
