# azure-pipelines.yml
trigger:
- master   # your repo uses master branch

pool:
  name: batch11   # Windows self-hosted agent pool

stages:
- stage: Build
  displayName: "Build and Publish Artifact"
  jobs:
    - job: BuildJob
      displayName: "Build Job"
      steps:
        # Step 1: Checkout repo
        - checkout: self

        # Step 2: Verify Java & Maven
        - powershell: |
            java -version
            mvn -version
          displayName: "Check Java & Maven"

        # Step 3: Run Maven build (inside Amazon folder)
        - powershell: |
            cd $(Build.SourcesDirectory)\Amazon
            mvn clean package -DskipTests
          displayName: "Maven Build"

        # Step 4: Copy JAR/WAR files to staging
        - task: CopyFiles@2
          displayName: "Copy build outputs"
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)\Amazon'
            Contents: '**\target\*.?(jar|war)'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        # Step 5: Publish artifacts
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifacts"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
