trigger:
- master   # your repo uses master branch

pool:
  name: batch11   # Windows self-hosted agent pool

stages:
# =====================
# Stage 1: Build
# =====================
- stage: Build
  displayName: "Build and Publish Artifact"
  jobs:
    - job: BuildJob
      displayName: "Build Job"
      steps:
        # Step 1: Checkout repo
        - checkout: self

        # Step 2: Verify Java & Maven
        - powershell: |
            java -version
            mvn -version
          displayName: "Check Java & Maven"

        # Step 3: Run Maven build (inside Amazon folder)
        - powershell: |
            cd $(Build.SourcesDirectory)\Amazon
            mvn clean package -DskipTests
          displayName: "Maven Build"

        # Step 4: Copy JAR/WAR files from all submodules
        - task: CopyFiles@2
          displayName: "Copy build outputs"
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)\Amazon'
            Contents: '**\target\*.jar;**\target\*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        # Step 5: Publish artifacts
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifacts"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

# =====================
# Stage 2: Deploy
# =====================
- stage: Deploy
  displayName: "Deploy to Tomcat"
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: "Deploy Job"
      steps:
        # Step 1: Download artifacts from Build stage
        - download: current
          artifact: drop

        # Step 2: Deploy WAR to Tomcat webapps
        - powershell: |
            # Look for WAR inside Amazon-Web\target (preferred web module)
            $warFile = Get-ChildItem "$(Pipeline.Workspace)\drop" -Recurse -Include *.war | Where-Object { $_.FullName -like "*Amazon-Web*" } | Select-Object -First 1
            
            if (-not $warFile) {
              Write-Error "No WAR file found in Amazon-Web target!"
              exit 1
            }
            
            Write-Host "Deploying WAR file: $($warFile.FullName)"
            
            # Adjust Tomcat installation path if different
            Copy-Item $warFile.FullName "C:\Tomcat\webapps\" -Force
          displayName: "Deploy WAR to Tomcat"
