trigger:
- main   # or master, change as per your default branch

pool:
  name: batch11   # your self-hosted Windows agent pool

stages:
# =============================
# Stage 1: Build & Publish
# =============================
- stage: Build
  displayName: "Build Stage"
  jobs:
    - job: BuildJob
      displayName: "Build Java Project"
      steps:
        - checkout: self
          fetchDepth: 1

        - task: Maven@4
          displayName: "Maven Package"
          inputs:
            mavenPomFile: "pom.xml"
            goals: "clean package"
            javaHomeOption: "JDKVersion"
            jdkVersionOption: "1.11"   # adjust if you use 17
            publishJUnitResults: true
            testResultsFiles: "**/surefire-reports/TEST-*.xml"

        - task: PublishBuildArtifacts@1
          displayName: "Publish Build Artifact"
          inputs:
            PathtoPublish: "$(System.DefaultWorkingDirectory)/Amazon/target"
            ArtifactName: "drop"
            publishLocation: "Container"

# =============================
# Stage 2: Deploy to Tomcat
# =============================
- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: "Deploy WAR to Tomcat"
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: "Download Artifact"
          inputs:
            buildType: "current"
            downloadType: "single"
            artifactName: "drop"
            downloadPath: "$(System.ArtifactsDirectory)"

        - powershell: |
            Write-Host "Copying WAR to Tomcat webapps..."
            Copy-Item "$(System.ArtifactsDirectory)\drop\*.war" "C:\Tomcat\webapps\" -Force
          displayName: "Copy WAR"

        - powershell: |
            Write-Host "Restarting Tomcat service..."
            net stop Tomcat9
            net start Tomcat9
          displayName: "Restart Tomcat"
