trigger:
- master

pool:
  name: batch11
  demands:
    - agent.name -equals lin1

stages:
- stage: Build
  displayName: "Build and Publish Artifact"
  jobs:
    - job: BuildJob
      displayName: "Build Job"
      steps:
        - checkout: self

        - script: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk maven
            java -version
            mvn -version
          displayName: "Install Java & Maven"

        - script: |
            cd $(Build.SourcesDirectory)/Amazon
            mvn clean install -DskipTests
          displayName: "Maven Multi-module Build"

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/Amazon/Amazon-Web/target'
            Contents: '*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
          displayName: "Copy WAR output"

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: "Publish Artifact"

- stage: Deploy
  displayName: "Deploy to Tomcat"
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: "Deploy Job"
      steps:
        - download: current
          artifact: drop

        - script: |
            # Install Apache Tomcat
            TOMCAT_VERSION=9.0.106
            INSTALL_DIR=/home/lin1/apache-tomcat-$TOMCAT_VERSION

            if [ ! -d "$INSTALL_DIR" ]; then
              wget https://downloads.apache.org/tomcat/tomcat-9/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
              tar -xzf apache
