trigger:
- master

pool:
  name: batch11
  demands:
    - agent.name -equals lin1

stages:
- stage: Build
  displayName: "Build and Publish Artifact"
  jobs:
    - job: BuildJob
      displayName: "Build Job"
      steps:
        - checkout: self
        - script: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            sudo apt-get install -y maven
            java -version
            mvn -version
          displayName: "Install Java & Maven and Check Versions"
        - script: |
            cd $(Build.SourcesDirectory)/Amazon
            mvn clean package -DskipTests
          displayName: "Maven Build"
        - task: CopyFiles@2
          displayName: "Copy WAR output"
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/Amazon/Amazon-Web/target'
            Contents: '*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifact"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

- stage: Deploy
  displayName: "Deploy to Tomcat"
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: "Deploy Job"
      steps:
        - download: current
          artifact: drop
        - script: |
            warFile=$(find "$(Pipeline.Workspace)/drop" -name "*.war" | head -n 1)
            if [ -z "$warFile" ]; then
              echo "ERROR: No WAR file found in artifact!"
              exit 1
            fi
            echo "Deploying WAR file: $warFile"
            tomcatPath="/home/lin1/apache-tomcat-9.0.106/webapps"
            cp -f "$warFile" "$tomcatPath/"
          displayName: "Deploy WAR to Tomcat"
        - script: |
            echo "Restarting Tomcat..."
            /home/lin1/apache-tomcat-9.0.106/bin/shutdown.sh || true
            sleep 5
            /home/lin1/apache-tomcat-9.0.106/bin/startup.sh
          displayName: "Restart Tomcat"
